### PR TITLE
kythe-proto: Vendor storage.proto file

### PR DESCRIPTION
**Pull request by mpickering**
This is the file from the v0.0.28 release tarball

### CODE REVIEW

**Comment by mpickering** [comment]
It's because of an updated proto-lens-protoc

**Comment by qrilka** [comment]
@robinp any updates on this one? And I wonder if we could get rid of `kythe` as a submodule altogether saving some time and space

**Comment by robinp** [comment]
This should be green now with the updated Travis config and Matthew's previous changes.

@mpickering could you also remove the .gitmodules and the top-level third_party directory?

**Comment by mpickering** [comment]
Just updated the branch to also remove the submodule.

**Comment by mpickering** [comment]
Can this be merged?

**Comment by ivan444** [comment]
Looks good. Merging.

**Pull request merged**
